// Generates src/tables.generated.ts from the census data tables:
//   docs/data/fingerprints.json — the §6.3/§6.4 equation-form matchers
//   docs/data/glossary.json     — the §6.5 gloss-noun dimension table
// The JSON files are the sources of truth (their positives, negatives and
// notes feed the tests); the generated module carries only what the runtime
// needs, so the extension bundle stays small and the patterns are never
// retyped by hand (a backslash lost in transit is a silent matcher).
import { readFileSync, writeFileSync, renameSync } from "node:fs"
import { fileURLToPath } from "node:url"

const root = new URL("../", import.meta.url)
const read = (p) => JSON.parse(readFileSync(new URL(p, root), "utf8"))

const rules = read("docs/data/fingerprints.json").map(({ positives, negatives, census, ...rule }) => rule)
const nouns = read("docs/data/glossary.json").nouns.map(({ note, ...noun }) => noun)

const out = `// GENERATED by scripts/gen-tables.mjs from docs/data/fingerprints.json and
// docs/data/glossary.json. Edit those files, then \`npm run gen:tables\`.

export type FingerprintImplies =
  | { flavored: string[] }
  | { keys: string[] }
  | { absorbing: [string, string][] }
  | { absorbsWithFactor: [string, string] }

export type FingerprintRule = {
  id: string
  label: string
  tex: string
  meaning: string
  /** Over normalizeTexForDetection() output. */
  pattern: string
  implies: FingerprintImplies
}

export const FINGERPRINT_RULES: FingerprintRule[] = ${JSON.stringify(rules, null, 2)}

export type GlossDim = (number | [number, number])[]

export type GlossNoun = {
  noun: string
  synonyms: string[]
  /** SI reading over (M, L, T, Θ, I); exact rationals as [n, d]. */
  dim: GlossDim
  si: string
  dimensionless?: boolean
  conventionDependent?: boolean
  gaussianDim?: GlossDim
  coordinateConventionDependent?: boolean
  dimensionDependsOnSpatialDimension?: boolean
  dimByD?: Record<string, GlossDim>
  ambiguous?: boolean
}

export const GLOSSARY_NOUNS: GlossNoun[] = ${JSON.stringify(nouns, null, 2)}
`

const target = fileURLToPath(new URL("src/tables.generated.ts", root))
writeFileSync(target + ".tmp", out, "utf8")
renameSync(target + ".tmp", target)
console.log(`wrote ${target}: ${rules.length} fingerprint rules, ${nouns.length} nouns`)
