// GENERATED by scripts/gen-tables.mjs from docs/data/fingerprints.json and
// docs/data/glossary.json. Edit those files, then `npm run gen:tables`.

export type FingerprintImplies =
  | { flavored: string[] }
  | { keys: string[] }
  | { absorbing: [string, string][] }
  | { absorbsWithFactor: [string, string] }

export type FingerprintRule = {
  id: string
  label: string
  tex: string
  meaning: string
  /** Over normalizeTexForDetection() output. */
  pattern: string
  implies: FingerprintImplies
}

export const FINGERPRINT_RULES: FingerprintRule[] = [
  {
    "id": "coulomb-4pi-eps0",
    "label": "Coulomb prefactor 1/(4πε₀)",
    "tex": "F = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q_1 q_2}{r^2}",
    "meaning": "4πε₀ under the fraction bar: SI, rationalized, ε₀ not absorbed",
    "pattern": "(?:/\\s*\\(?\\s*4\\s*pi\\s*epsilon0|\\(\\s*4\\s*pi\\s*epsilon0\\s*\\)\\s*\\^\\s*\\{?\\s*-)",
    "implies": {
      "flavored": [
        "si"
      ]
    }
  },
  {
    "id": "coulomb-emu-c2",
    "label": "Coulomb force with an explicit c²",
    "tex": "F = c^2\\,\\frac{q_1 q_2}{r^2}",
    "meaning": "c² in Coulomb's law: EMU, the family's most diagnostic single equation",
    "pattern": "c\\s*\\^\\s*\\{?\\s*2\\s*\\}?\\s*\\)?\\s*\\(?\\s*q[^=]{0,30}/\\s*\\(?\\s*r\\s*\\^\\s*\\{?\\s*2",
    "implies": {
      "flavored": [
        "emu"
      ]
    }
  },
  {
    "id": "gauss-unrationalized",
    "label": "Gauss law with 4πρ",
    "tex": "\\nabla\\cdot\\mathbf{D} = 4\\pi\\rho",
    "meaning": "4πρ on the source: unrationalized — Gaussian, ESU, or EMU",
    "pattern": "\\\\nabla\\s*\\\\cdot[^=]{0,25}=\\s*4\\s*pi\\s*(?:\\\\rho|ρ)",
    "implies": {
      "flavored": [
        "gaussian",
        "esu",
        "emu"
      ]
    }
  },
  {
    "id": "gauss-rationalized",
    "label": "Gauss law with bare ρ",
    "tex": "\\nabla\\cdot\\mathbf{D} = \\rho",
    "meaning": "no 4π on the source: rationalized — SI or Heaviside–Lorentz",
    "pattern": "\\\\nabla\\s*\\\\cdot[^=]{0,25}=\\s*(?:\\\\rho|ρ)(?![A-Za-z])",
    "implies": {
      "flavored": [
        "si",
        "heaviside-lorentz"
      ]
    }
  },
  {
    "id": "ampere-4pi-over-c",
    "label": "Ampère–Maxwell with (4π/c)J",
    "tex": "\\nabla\\times\\mathbf{H} = \\frac{4\\pi}{c}\\mathbf{J} + \\frac{1}{c}\\frac{\\partial\\mathbf{D}}{\\partial t}",
    "meaning": "4π/c on the current: Gaussian — unrationalized plus the c-rider",
    "pattern": "(?<![0-9])4\\s*pi\\s*\\)?[^=G]{0,12}?/\\s*\\(?\\s*c(?![A-Za-z_0-9^])",
    "implies": {
      "flavored": [
        "gaussian"
      ]
    }
  },
  {
    "id": "ampere-4pi-j",
    "label": "Ampère–Maxwell with 4πJ and no 1/c",
    "tex": "\\nabla\\times\\mathbf{H} = 4\\pi\\mathbf{J} + \\frac{\\partial\\mathbf{D}}{\\partial t}",
    "meaning": "4πJ with no c-rider: ESU or EMU, never Gaussian",
    "pattern": "\\\\nabla\\s*\\\\times[^=]{0,25}=\\s*4\\s*pi\\s*(?![^=]{0,12}/\\s*c(?![A-Za-z_0-9]))[^=]{0,15}?J(?![A-Za-z])",
    "implies": {
      "flavored": [
        "esu",
        "emu"
      ]
    }
  },
  {
    "id": "ampere-si",
    "label": "Ampère–Maxwell with J + Ḋ",
    "tex": "\\nabla\\times\\mathbf{H} = \\mathbf{J} + \\frac{\\partial\\mathbf{D}}{\\partial t}",
    "meaning": "current with neither 4π nor 1/c: SI, asserted positively",
    "pattern": "\\\\nabla\\s*\\\\times[^=]{0,25}=\\s*(?:mu0\\s*)?(?:\\\\[a-zA-Z]+\\s*)?\\{?\\s*J\\s*\\}?\\s*\\+",
    "implies": {
      "flavored": [
        "si"
      ]
    }
  },
  {
    "id": "ampere-hl",
    "label": "Ampère–Maxwell with (1/c)(J + Ḋ)",
    "tex": "\\nabla\\times\\mathbf{H} = \\frac{1}{c}\\left(\\mathbf{J} + \\dot{\\mathbf{D}}\\right)",
    "meaning": "1/c on the whole source, no 4π: Heaviside–Lorentz",
    "pattern": "\\\\nabla\\s*\\\\times[^=]{0,25}=\\s*\\(?\\s*1\\s*\\)?\\s*/\\s*\\(?\\s*c\\s*\\)?\\s*\\(?\\s*(?:\\\\[a-zA-Z]+\\s*)?\\{?\\s*J(?![A-Za-z])",
    "implies": {
      "flavored": [
        "heaviside-lorentz"
      ]
    }
  },
  {
    "id": "alpha-hl",
    "label": "α = e²/4π",
    "tex": "\\alpha = \\frac{e^2}{4\\pi}",
    "meaning": "4π but no ε₀ under e²: Heaviside–Lorentz",
    "pattern": "(?<![A-Za-z])alpha(?![A-Za-z_'])\\s*=\\s*\\(?\\s*e\\s*\\^\\s*\\{?\\s*2\\s*\\}?\\s*\\)?\\s*/\\s*\\(?\\s*4\\s*pi(?!\\s*epsilon0)",
    "implies": {
      "flavored": [
        "heaviside-lorentz"
      ]
    }
  },
  {
    "id": "alpha-gaussian",
    "label": "α = e²/ħc",
    "tex": "\\alpha = \\frac{e^2}{\\hbar c}",
    "meaning": "e²/ħc with no 4π and no ε₀: Gaussian",
    "pattern": "(?<![A-Za-z])alpha(?![A-Za-z_'])\\s*=\\s*\\(?\\s*e\\s*\\^\\s*\\{?\\s*2\\s*\\}?\\s*\\)?\\s*/\\s*\\(?\\s*hbar\\s*c(?![A-Za-z_0-9])",
    "implies": {
      "flavored": [
        "gaussian"
      ]
    }
  },
  {
    "id": "maxwell-lagrangian-16pi",
    "label": "−F²/16π",
    "tex": "\\mathcal{L} = -\\frac{1}{16\\pi}F_{\\mu\\nu}F^{\\mu\\nu}",
    "meaning": "16π normalizing F²: Gaussian field-strength convention",
    "pattern": "(?:F(?![A-Za-z])[^=]{0,40}(?<![0-9])16\\s*pi(?!\\s*G(?![A-Za-z_]))|(?<![0-9])16\\s*pi\\s*(?!\\s*G(?![A-Za-z_]))\\)?\\s*[^=]{0,8}F(?![A-Za-z]))",
    "implies": {
      "flavored": [
        "gaussian"
      ]
    }
  },
  {
    "id": "maxwell-lagrangian-quarter",
    "label": "−¼F²",
    "tex": "\\mathcal{L} = -\\frac{1}{4}F_{\\mu\\nu}F^{\\mu\\nu}",
    "meaning": "¼ normalizing F²: rationalized — SI or Heaviside–Lorentz",
    "pattern": "-\\s*(?:\\(\\s*1\\s*\\)\\s*/\\s*\\(\\s*4\\s*\\)|\\\\[dt]?frac\\s*\\{?\\s*1\\s*\\}?\\s*\\{?\\s*4\\s*\\}?|1\\s*/\\s*4)(?!\\s*pi)\\s*[^=]{0,2}F(?![A-Za-z])",
    "implies": {
      "flavored": [
        "si",
        "heaviside-lorentz"
      ]
    }
  },
  {
    "id": "si-constants-explicit",
    "label": "μ₀/4π in a coupling, or μ_B with no 1/c",
    "tex": "\\mathbf{B} = \\frac{\\mu_0}{4\\pi}\\int\\frac{I\\,d\\boldsymbol{\\ell}\\times\\hat{\\mathbf{r}}}{r^2},\\qquad \\mu_B = \\frac{e\\hbar}{2m_e}",
    "meaning": "μ₀/4π printed, or a Zeeman coupling with no 1/c: SI asserted",
    "pattern": "(?:mu0\\s*\\)?\\s*/\\s*\\(?\\s*4\\s*pi|e\\s*hbar\\s*\\)?\\s*/\\s*\\(?\\s*2\\s*(?:me|m\\s*_\\s*\\{?\\s*e\\s*\\}?)\\s*\\)?(?!\\s*c(?![A-Za-z_0-9])))",
    "implies": {
      "flavored": [
        "si"
      ]
    }
  },
  {
    "id": "einstein-hilbert-c4-16piG",
    "label": "Einstein–Hilbert prefactor c⁴/16πG",
    "tex": "S = \\frac{c^4}{16\\pi G}\\int d^4x\\,\\sqrt{-g}\\,R",
    "meaning": "c and G printed in the action prefactor: neither is absorbed",
    "pattern": "c\\s*\\^\\s*\\{?\\s*[34]\\s*\\}?\\s*\\)?\\s*/\\s*\\(?\\s*16\\s*pi\\s*G(?![A-Za-z_])",
    "implies": {
      "keys": [
        "si",
        "gaussian",
        "esu",
        "emu",
        "heaviside-lorentz",
        "magnetism-emu",
        "hartree",
        "rydberg",
        "hartree-gaussian",
        "effective-au",
        "kb-only",
        "lj-reduced",
        "chaos-mw",
        "trap-units",
        "ns-inertial",
        "lattice-model",
        "gpe-healing"
      ]
    }
  },
  {
    "id": "einstein-hilbert-1-over-16pi",
    "label": "Einstein–Hilbert prefactor 1/16π",
    "tex": "S = \\frac{1}{16\\pi}\\int d^4x\\,\\sqrt{-g}\\,R",
    "meaning": "16π with no G on √−g R: G = c = 1, Cluster A",
    "pattern": "/\\s*\\(?\\s*16\\s*pi\\s*(?!\\s*G(?![A-Za-z_]))\\)?\\s*[^=]{0,30}\\\\sqrt\\s*\\{?\\s*-\\s*g(?![A-Za-z])",
    "implies": {
      "absorbing": [
        [
          "c",
          "c"
        ],
        [
          "G",
          "G"
        ]
      ]
    }
  },
  {
    "id": "einstein-hilbert-half",
    "label": "Einstein–Hilbert prefactor ½",
    "tex": "S = \\frac{1}{2}\\int d^4x\\,\\sqrt{-g}\\,(R - 2\\Lambda)",
    "meaning": "½ on √−g R: 8πG = 1",
    "pattern": "\\(?\\s*1\\s*\\)?\\s*/\\s*\\(?\\s*2\\s*\\)?\\s*(?=\\\\int|\\\\sqrt|d\\s*\\^)[^=]{0,40}\\\\sqrt\\s*\\{?\\s*-\\s*g\\s*\\}?[^=]{0,12}R(?![A-Za-z])",
    "implies": {
      "absorbsWithFactor": [
        "G",
        "8\\pi"
      ]
    }
  },
  {
    "id": "einstein-hilbert-bare",
    "label": "Bare ∫√−g (R − 2Λ), no prefactor",
    "tex": "S = \\int d^4x\\,\\sqrt{-g}\\,(R - 2\\Lambda)",
    "meaning": "no prefactor at all on √−g R: 16πG = 1",
    "pattern": "=\\s*\\\\int[^=]{0,25}\\\\sqrt\\s*\\{?\\s*-\\s*g\\s*\\}?[^=0-9\\\\]{0,12}R(?![A-Za-z])(?!\\s*\\}?\\s*\\)?\\s*/)",
    "implies": {
      "absorbsWithFactor": [
        "G",
        "16\\pi"
      ]
    }
  },
  {
    "id": "bh-thermo-planck",
    "label": "S = A/4 and T_H = 1/8πM",
    "tex": "S = \\frac{A}{4},\\qquad T_H = \\frac{1}{8\\pi M}",
    "meaning": "bare A/4 or 1/8πM: Planck units, ħ = c = G = 1",
    "pattern": "(?:(?<![A-Za-z])S[^=]{0,14}=\\s*\\(?\\s*A\\s*\\)?\\s*/\\s*\\(?\\s*4\\s*\\)?(?![0-9A-Za-z\\\\])|(?<![A-Za-z])T[^=]{0,14}=\\s*\\(?\\s*1\\s*\\)?\\s*/\\s*\\(?\\s*8\\s*pi\\s*M(?![A-Za-z_]))",
    "implies": {
      "absorbing": [
        [
          "\\hbar",
          "hbar"
        ],
        [
          "c",
          "c"
        ],
        [
          "G",
          "G"
        ]
      ]
    }
  },
  {
    "id": "bh-entropy-4pi-a",
    "label": "S = 4πA",
    "tex": "S = 4\\pi A",
    "meaning": "entropy 4πA: 16πG = 1",
    "pattern": "(?<![A-Za-z])S[^=]{0,14}=\\s*4\\s*pi\\s*A(?![A-Za-z])",
    "implies": {
      "absorbsWithFactor": [
        "G",
        "16\\pi"
      ]
    }
  },
  {
    "id": "covariant-source-4pi-j",
    "label": "∂_μF^{μν} = 4πJ^ν",
    "tex": "\\partial_\\mu F^{\\mu\\nu} = \\frac{4\\pi}{c}J^\\nu",
    "meaning": "4π on the covariant source: Gaussian",
    "pattern": "\\\\partial[^=]{0,20}F[^=]{0,20}=\\s*(?:\\(\\s*4\\s*pi\\s*\\)\\s*/\\s*\\(?\\s*c\\s*\\)?|4\\s*pi\\s*/\\s*c|4\\s*pi)\\s*[^=]{0,12}J(?![A-Za-z])",
    "implies": {
      "flavored": [
        "gaussian"
      ]
    }
  }
]

export type GlossDim = (number | [number, number])[]

export type GlossNoun = {
  noun: string
  synonyms: string[]
  /** SI reading over (M, L, T, Θ, I); exact rationals as [n, d]. */
  dim: GlossDim
  si: string
  dimensionless?: boolean
  conventionDependent?: boolean
  gaussianDim?: GlossDim
  coordinateConventionDependent?: boolean
  dimensionDependsOnSpatialDimension?: boolean
  dimByD?: Record<string, GlossDim>
  ambiguous?: boolean
}

export const GLOSSARY_NOUNS: GlossNoun[] = [
  {
    "noun": "mass",
    "synonyms": [
      "rest mass",
      "masses",
      "total mass",
      "particle mass",
      "inertial mass"
    ],
    "dim": [
      1,
      0,
      0,
      0,
      0
    ],
    "si": "kg"
  },
  {
    "noun": "length",
    "synonyms": [
      "distance",
      "separation",
      "displacement",
      "size",
      "scale",
      "lengths",
      "distances",
      "length scale",
      "characteristic length"
    ],
    "dim": [
      0,
      1,
      0,
      0,
      0
    ],
    "si": "m"
  },
  {
    "noun": "radius",
    "synonyms": [
      "radii",
      "radial coordinate",
      "radial distance",
      "orbital radius"
    ],
    "dim": [
      0,
      1,
      0,
      0,
      0
    ],
    "si": "m"
  },
  {
    "noun": "time",
    "synonyms": [
      "duration",
      "period",
      "timescale",
      "time scale",
      "times",
      "coordinate time",
      "proper time",
      "orbital period"
    ],
    "dim": [
      0,
      0,
      1,
      0,
      0
    ],
    "si": "s"
  },
  {
    "noun": "frequency",
    "synonyms": [
      "frequencies",
      "linear frequency",
      "cyclic frequency",
      "rotation frequency"
    ],
    "dim": [
      0,
      0,
      -1,
      0,
      0
    ],
    "si": "Hz"
  },
  {
    "noun": "angular frequency",
    "synonyms": [
      "angular velocity",
      "angular frequencies",
      "circular frequency",
      "rotation rate",
      "spin rate"
    ],
    "dim": [
      0,
      0,
      -1,
      0,
      0
    ],
    "si": "rad s⁻¹"
  },
  {
    "noun": "velocity",
    "synonyms": [
      "speed",
      "velocities",
      "speeds",
      "flow velocity",
      "orbital velocity",
      "recession velocity"
    ],
    "dim": [
      0,
      1,
      -1,
      0,
      0
    ],
    "si": "m s⁻¹"
  },
  {
    "noun": "acceleration",
    "synonyms": [
      "accelerations",
      "proper acceleration",
      "gravitational acceleration",
      "surface gravity"
    ],
    "dim": [
      0,
      1,
      -2,
      0,
      0
    ],
    "si": "m s⁻²"
  },
  {
    "noun": "force",
    "synonyms": [
      "forces",
      "restoring force",
      "applied force"
    ],
    "dim": [
      1,
      1,
      -2,
      0,
      0
    ],
    "si": "N"
  },
  {
    "noun": "energy",
    "synonyms": [
      "energies",
      "total energy",
      "kinetic energy",
      "potential energy",
      "binding energy",
      "Fermi energy",
      "energy scale"
    ],
    "dim": [
      1,
      2,
      -2,
      0,
      0
    ],
    "si": "J"
  },
  {
    "noun": "work",
    "synonyms": [
      "work done"
    ],
    "dim": [
      1,
      2,
      -2,
      0,
      0
    ],
    "si": "J"
  },
  {
    "noun": "power",
    "synonyms": [
      "radiated power",
      "output power",
      "luminosity"
    ],
    "dim": [
      1,
      2,
      -3,
      0,
      0
    ],
    "si": "W"
  },
  {
    "noun": "momentum",
    "synonyms": [
      "linear momentum",
      "momenta",
      "canonical momentum"
    ],
    "dim": [
      1,
      1,
      -1,
      0,
      0
    ],
    "si": "kg m s⁻¹"
  },
  {
    "noun": "angular momentum",
    "synonyms": [
      "spin angular momentum",
      "orbital angular momentum",
      "spin"
    ],
    "dim": [
      1,
      2,
      -1,
      0,
      0
    ],
    "si": "kg m² s⁻¹"
  },
  {
    "noun": "action",
    "synonyms": [
      "Euclidean action",
      "on-shell action"
    ],
    "dim": [
      1,
      2,
      -1,
      0,
      0
    ],
    "si": "J s"
  },
  {
    "noun": "pressure",
    "synonyms": [
      "stress",
      "stresses",
      "pressures",
      "gas pressure",
      "radiation pressure"
    ],
    "dim": [
      1,
      -1,
      -2,
      0,
      0
    ],
    "si": "Pa"
  },
  {
    "noun": "mass density",
    "synonyms": [
      "density",
      "densities",
      "matter density",
      "rest-mass density",
      "critical density",
      "bulk density"
    ],
    "dim": [
      1,
      -3,
      0,
      0,
      0
    ],
    "si": "kg m⁻³"
  },
  {
    "noun": "number density",
    "synonyms": [
      "particle density",
      "electron density",
      "column density",
      "number densities"
    ],
    "dim": [
      0,
      -3,
      0,
      0,
      0
    ],
    "si": "m⁻³"
  },
  {
    "noun": "surface density",
    "synonyms": [
      "surface mass density",
      "areal density",
      "column mass density",
      "disc surface density"
    ],
    "dim": [
      1,
      -2,
      0,
      0,
      0
    ],
    "si": "kg m⁻²"
  },
  {
    "noun": "torque",
    "synonyms": [
      "torques",
      "moment of force"
    ],
    "dim": [
      1,
      2,
      -2,
      0,
      0
    ],
    "si": "N m"
  },
  {
    "noun": "moment of inertia",
    "synonyms": [
      "inertia tensor",
      "moments of inertia"
    ],
    "dim": [
      1,
      2,
      0,
      0,
      0
    ],
    "si": "kg m²"
  },
  {
    "noun": "area",
    "synonyms": [
      "areas",
      "surface area",
      "cross-sectional area",
      "horizon area"
    ],
    "dim": [
      0,
      2,
      0,
      0,
      0
    ],
    "si": "m²"
  },
  {
    "noun": "volume",
    "synonyms": [
      "volumes",
      "mode volume",
      "comoving volume"
    ],
    "dim": [
      0,
      3,
      0,
      0,
      0
    ],
    "si": "m³"
  },
  {
    "noun": "cross section",
    "synonyms": [
      "cross-section",
      "cross sections",
      "scattering cross section",
      "total cross section",
      "partial cross section"
    ],
    "dim": [
      0,
      2,
      0,
      0,
      0
    ],
    "si": "m²"
  },
  {
    "noun": "energy density",
    "synonyms": [
      "energy densities",
      "vacuum energy density",
      "radiation energy density"
    ],
    "dim": [
      1,
      -1,
      -2,
      0,
      0
    ],
    "si": "J m⁻³"
  },
  {
    "noun": "angle",
    "synonyms": [
      "polar angle",
      "azimuthal angle",
      "scattering angle",
      "inclination",
      "phase",
      "angles"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "rad",
    "dimensionless": true
  },
  {
    "noun": "solid angle",
    "synonyms": [
      "solid angles"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "sr",
    "dimensionless": true
  },
  {
    "noun": "diffusion coefficient",
    "synonyms": [
      "diffusivity",
      "diffusion constant",
      "kinematic viscosity",
      "thermal diffusivity"
    ],
    "dim": [
      0,
      2,
      -1,
      0,
      0
    ],
    "si": "m² s⁻¹"
  },
  {
    "noun": "dynamic viscosity",
    "synonyms": [
      "shear viscosity",
      "viscosity"
    ],
    "dim": [
      1,
      -1,
      -1,
      0,
      0
    ],
    "si": "Pa s"
  },
  {
    "noun": "strain",
    "synonyms": [
      "gravitational-wave strain",
      "strain amplitude",
      "fractional deformation"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "1",
    "dimensionless": true
  },
  {
    "noun": "temperature",
    "synonyms": [
      "temperatures",
      "brightness temperature",
      "effective temperature",
      "Hawking temperature",
      "ambient temperature"
    ],
    "dim": [
      0,
      0,
      0,
      1,
      0
    ],
    "si": "K"
  },
  {
    "noun": "entropy",
    "synonyms": [
      "entropies",
      "thermodynamic entropy",
      "Bekenstein-Hawking entropy"
    ],
    "dim": [
      1,
      2,
      -2,
      -1,
      0
    ],
    "si": "J K⁻¹"
  },
  {
    "noun": "heat capacity",
    "synonyms": [
      "specific heat",
      "specific heat capacity",
      "heat capacities"
    ],
    "dim": [
      1,
      2,
      -2,
      -1,
      0
    ],
    "si": "J K⁻¹"
  },
  {
    "noun": "chemical potential",
    "synonyms": [
      "chemical potentials",
      "Fermi level"
    ],
    "dim": [
      1,
      2,
      -2,
      0,
      0
    ],
    "si": "J"
  },
  {
    "noun": "charge",
    "synonyms": [
      "electric charge",
      "charges",
      "total charge",
      "elementary charge"
    ],
    "dim": [
      0,
      0,
      1,
      0,
      1
    ],
    "si": "C",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        3,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "current",
    "synonyms": [
      "electric current",
      "currents"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      1
    ],
    "si": "A",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        3,
        2
      ],
      -2,
      0,
      0
    ]
  },
  {
    "noun": "voltage",
    "synonyms": [
      "potential",
      "electric potential",
      "electrostatic potential",
      "potential difference",
      "bias voltage",
      "electromotive force"
    ],
    "dim": [
      1,
      2,
      -3,
      0,
      -1
    ],
    "si": "V",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        1,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "electric field",
    "synonyms": [
      "electric field strength",
      "electric fields",
      "applied field"
    ],
    "dim": [
      1,
      1,
      -3,
      0,
      -1
    ],
    "si": "V m⁻¹",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        -1,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "magnetic field",
    "synonyms": [
      "magnetic flux density",
      "magnetic induction",
      "magnetic fields",
      "field strength B"
    ],
    "dim": [
      1,
      0,
      -2,
      0,
      -1
    ],
    "si": "T",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        -1,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "magnetic field H",
    "synonyms": [
      "magnetizing field",
      "auxiliary magnetic field",
      "H-field",
      "magnetic field strength"
    ],
    "dim": [
      0,
      -1,
      0,
      0,
      1
    ],
    "si": "A m⁻¹",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        -1,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "magnetic flux",
    "synonyms": [
      "flux",
      "magnetic fluxes",
      "flux quantum"
    ],
    "dim": [
      1,
      2,
      -2,
      0,
      -1
    ],
    "si": "Wb",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        3,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "capacitance",
    "synonyms": [
      "capacitances",
      "gate capacitance"
    ],
    "dim": [
      -1,
      -2,
      4,
      0,
      2
    ],
    "si": "F",
    "conventionDependent": true,
    "gaussianDim": [
      0,
      1,
      0,
      0,
      0
    ]
  },
  {
    "noun": "resistance",
    "synonyms": [
      "impedance",
      "resistances",
      "sheet resistance"
    ],
    "dim": [
      1,
      2,
      -3,
      0,
      -2
    ],
    "si": "Ω",
    "conventionDependent": true,
    "gaussianDim": [
      0,
      -1,
      1,
      0,
      0
    ]
  },
  {
    "noun": "inductance",
    "synonyms": [
      "self-inductance",
      "mutual inductance",
      "inductances"
    ],
    "dim": [
      1,
      2,
      -2,
      0,
      -2
    ],
    "si": "H",
    "conventionDependent": true,
    "gaussianDim": [
      0,
      -1,
      2,
      0,
      0
    ]
  },
  {
    "noun": "conductivity",
    "synonyms": [
      "electrical conductivity",
      "conductance per length",
      "conductivities"
    ],
    "dim": [
      -1,
      -3,
      3,
      0,
      2
    ],
    "si": "S m⁻¹",
    "conventionDependent": true,
    "gaussianDim": [
      0,
      0,
      -1,
      0,
      0
    ]
  },
  {
    "noun": "resistivity",
    "synonyms": [
      "electrical resistivity",
      "resistivities"
    ],
    "dim": [
      1,
      3,
      -3,
      0,
      -2
    ],
    "si": "Ω m",
    "conventionDependent": true,
    "gaussianDim": [
      0,
      0,
      1,
      0,
      0
    ]
  },
  {
    "noun": "permittivity",
    "synonyms": [
      "dielectric permittivity",
      "vacuum permittivity",
      "dielectric constant"
    ],
    "dim": [
      -1,
      -3,
      4,
      0,
      2
    ],
    "si": "F m⁻¹",
    "conventionDependent": true,
    "gaussianDim": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  {
    "noun": "permeability",
    "synonyms": [
      "magnetic permeability",
      "vacuum permeability"
    ],
    "dim": [
      1,
      1,
      -2,
      0,
      -2
    ],
    "si": "H m⁻¹",
    "conventionDependent": true,
    "gaussianDim": [
      0,
      0,
      0,
      0,
      0
    ]
  },
  {
    "noun": "electric dipole moment",
    "synonyms": [
      "dipole moment",
      "transition dipole moment",
      "electric dipole"
    ],
    "dim": [
      0,
      1,
      1,
      0,
      1
    ],
    "si": "C m",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        5,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "magnetic moment",
    "synonyms": [
      "magnetic dipole moment",
      "magnetic moments",
      "Bohr magneton"
    ],
    "dim": [
      0,
      2,
      0,
      0,
      1
    ],
    "si": "A m²",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        5,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "polarization",
    "synonyms": [
      "electric polarization",
      "polarization density",
      "dielectric polarization"
    ],
    "dim": [
      0,
      -2,
      1,
      0,
      1
    ],
    "si": "C m⁻²",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        -1,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "magnetization",
    "synonyms": [
      "magnetisation",
      "magnetization density",
      "magnetic moment per volume"
    ],
    "dim": [
      0,
      -1,
      0,
      0,
      1
    ],
    "si": "A m⁻¹",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        -1,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "current density",
    "synonyms": [
      "current densities",
      "surface current density"
    ],
    "dim": [
      0,
      -2,
      0,
      0,
      1
    ],
    "si": "A m⁻²",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        -1,
        2
      ],
      -2,
      0,
      0
    ]
  },
  {
    "noun": "charge density",
    "synonyms": [
      "charge densities",
      "volume charge density",
      "surface charge density"
    ],
    "dim": [
      0,
      -3,
      1,
      0,
      1
    ],
    "si": "C m⁻³",
    "conventionDependent": true,
    "gaussianDim": [
      [
        1,
        2
      ],
      [
        -3,
        2
      ],
      -1,
      0,
      0
    ]
  },
  {
    "noun": "wavelength",
    "synonyms": [
      "wavelengths",
      "de Broglie wavelength",
      "Compton wavelength"
    ],
    "dim": [
      0,
      1,
      0,
      0,
      0
    ],
    "si": "m"
  },
  {
    "noun": "wavenumber",
    "synonyms": [
      "wave number",
      "wave vector",
      "wavevector",
      "spatial frequency",
      "wavenumbers"
    ],
    "dim": [
      0,
      -1,
      0,
      0,
      0
    ],
    "si": "m⁻¹"
  },
  {
    "noun": "refractive index",
    "synonyms": [
      "index of refraction",
      "refractive indices"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "1",
    "dimensionless": true
  },
  {
    "noun": "intensity",
    "synonyms": [
      "intensities",
      "beam intensity",
      "laser intensity"
    ],
    "dim": [
      1,
      0,
      -3,
      0,
      0
    ],
    "si": "W m⁻²",
    "ambiguous": true
  },
  {
    "noun": "irradiance",
    "synonyms": [
      "flux density (radiometric)",
      "energy flux",
      "power per unit area"
    ],
    "dim": [
      1,
      0,
      -3,
      0,
      0
    ],
    "si": "W m⁻²"
  },
  {
    "noun": "luminosity",
    "synonyms": [
      "bolometric luminosity",
      "luminosities",
      "radiated power"
    ],
    "dim": [
      1,
      2,
      -3,
      0,
      0
    ],
    "si": "W"
  },
  {
    "noun": "flux density",
    "synonyms": [
      "spectral flux density",
      "flux densities"
    ],
    "dim": [
      1,
      0,
      -2,
      0,
      0
    ],
    "si": "Jy",
    "ambiguous": true
  },
  {
    "noun": "optical depth",
    "synonyms": [
      "optical depths",
      "opacity depth"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "1",
    "dimensionless": true
  },
  {
    "noun": "metric",
    "synonyms": [
      "metric tensor",
      "spacetime metric",
      "line element coefficient"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "1",
    "dimensionless": true,
    "coordinateConventionDependent": true
  },
  {
    "noun": "Schwarzschild radius",
    "synonyms": [
      "gravitational radius",
      "horizon radius",
      "event-horizon radius"
    ],
    "dim": [
      0,
      1,
      0,
      0,
      0
    ],
    "si": "m"
  },
  {
    "noun": "gravitational potential",
    "synonyms": [
      "Newtonian potential",
      "gravitational potentials",
      "Bardeen potential"
    ],
    "dim": [
      0,
      2,
      -2,
      0,
      0
    ],
    "si": "m² s⁻²"
  },
  {
    "noun": "Hubble parameter",
    "synonyms": [
      "Hubble constant",
      "Hubble rate",
      "expansion rate"
    ],
    "dim": [
      0,
      0,
      -1,
      0,
      0
    ],
    "si": "s⁻¹"
  },
  {
    "noun": "cosmological constant",
    "synonyms": [
      "dark-energy constant",
      "vacuum curvature"
    ],
    "dim": [
      0,
      -2,
      0,
      0,
      0
    ],
    "si": "m⁻²",
    "ambiguous": true
  },
  {
    "noun": "redshift",
    "synonyms": [
      "cosmological redshift",
      "redshifts"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "1",
    "dimensionless": true
  },
  {
    "noun": "scale factor",
    "synonyms": [
      "cosmological scale factor",
      "expansion factor"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "1",
    "dimensionless": true,
    "coordinateConventionDependent": true
  },
  {
    "noun": "surface gravity",
    "synonyms": [
      "horizon surface gravity"
    ],
    "dim": [
      0,
      1,
      -2,
      0,
      0
    ],
    "si": "m s⁻²",
    "ambiguous": true
  },
  {
    "noun": "wavefunction",
    "synonyms": [
      "wave function",
      "state function",
      "field amplitude",
      "wavefunctions"
    ],
    "dim": [
      0,
      [
        -3,
        2
      ],
      0,
      0,
      0
    ],
    "si": "m^(-3/2)",
    "dimensionDependsOnSpatialDimension": true,
    "dimByD": {
      "1": [
        0,
        [
          -1,
          2
        ],
        0,
        0,
        0
      ],
      "2": [
        0,
        -1,
        0,
        0,
        0
      ],
      "3": [
        0,
        [
          -3,
          2
        ],
        0,
        0,
        0
      ]
    }
  },
  {
    "noun": "coupling constant",
    "synonyms": [
      "coupling",
      "couplings",
      "gauge coupling",
      "interaction strength",
      "fine-structure constant"
    ],
    "dim": [
      0,
      0,
      0,
      0,
      0
    ],
    "si": "1",
    "dimensionless": true,
    "ambiguous": true
  },
  {
    "noun": "decay width",
    "synonyms": [
      "width",
      "linewidth",
      "resonance width",
      "partial width",
      "total width"
    ],
    "dim": [
      1,
      2,
      -2,
      0,
      0
    ],
    "si": "J",
    "ambiguous": true
  },
  {
    "noun": "decay rate",
    "synonyms": [
      "rate",
      "transition rate",
      "relaxation rate",
      "scattering rate"
    ],
    "dim": [
      0,
      0,
      -1,
      0,
      0
    ],
    "si": "s⁻¹"
  },
  {
    "noun": "lifetime",
    "synonyms": [
      "mean lifetime",
      "half-life",
      "coherence time",
      "relaxation time",
      "lifetimes"
    ],
    "dim": [
      0,
      0,
      1,
      0,
      0
    ],
    "si": "s"
  },
  {
    "noun": "scattering length",
    "synonyms": [
      "s-wave scattering length",
      "scattering lengths"
    ],
    "dim": [
      0,
      1,
      0,
      0,
      0
    ],
    "si": "m"
  }
]
